In [1]:
import numpy as np
from pickle import load

In [2]:
# Loading pretrained classifiers from pickle file

scaler = load(open('models/standard_scaler.pkl', 'rb'))
knn_classifier = load(open('models/knn_model.pkl', 'rb'))
lr_classifier = load(open('models/lr_model.pkl', 'rb'))
nb_classifier = load(open('models/nb_model.pkl', 'rb'))
dt_classifier = load(open('models/dt_model.pkl', 'rb'))
sv_classifier = load(open('models/sv_model.pkl', 'rb'))

In [3]:
# Read the Query Data

print("Enter Water Details")
ph = float(input('Enter the ph: '))
hd = float(input('Enter the Hardness: '))
sd = float(input('Enter the Solids: '))
cl = float(input('Enter the Chloramines: '))
sl = float(input('Enter the Sulphate: '))
cd = float(input('Enter the Conductivity: '))
oc = float(input('Enter the Organic_carbon: '))
tm = float(input('Enter the Trihalomethanes: '))
tb = float(input('Enter the Turbidity: '))

Enter Water Details
Enter the ph: 7
Enter the Hardness: 200
Enter the Solids: 18000
Enter the Chloramines: 8
Enter the Sulphate: 320
Enter the Conductivity: 400
Enter the Organic_carbon: 13
Enter the Trihalomethanes: 70
Enter the Turbidity: 4.56


### Converting the values to 2D Array

In [4]:
query_point = np.array([ph,hd,sd,cl,sl,cd,oc,tm,tb])

In [5]:
query_point

array([7.00e+00, 2.00e+02, 1.80e+04, 8.00e+00, 3.20e+02, 4.00e+02,
       1.30e+01, 7.00e+01, 4.56e+00])

In [6]:
query_point.reshape(1, -1)

array([[7.00e+00, 2.00e+02, 1.80e+04, 8.00e+00, 3.20e+02, 4.00e+02,
        1.30e+01, 7.00e+01, 4.56e+00]])

In [7]:
query_point = query_point.reshape(1, -1)

query_point

array([[7.00e+00, 2.00e+02, 1.80e+04, 8.00e+00, 3.20e+02, 4.00e+02,
        1.30e+01, 7.00e+01, 4.56e+00]])

In [8]:
query_point_transformed = scaler.transform(query_point)

query_point_transformed

C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.06511714,  0.14252652, -0.46035316,  0.54507919, -0.32193494,
        -0.33408992, -0.39642132,  0.21384611,  0.77685563]])

In [9]:
knn_classifier.predict(query_point_transformed)

C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [10]:
lr_classifier.predict(query_point_transformed)

C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [11]:
nb_classifier.predict(query_point_transformed)

C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [12]:
dt_classifier.predict(query_point_transformed)

C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [13]:
sv_classifier.predict(query_point_transformed)

C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

## Production Ready Code

In [14]:
print("Enter Water Details")
ph = float(input('Enter the ph: '))
hd = float(input('Enter the Hardness: '))
sd = float(input('Enter the Solids: '))
cl = float(input('Enter the Chloramines: '))
sl = float(input('Enter the Sulphate: '))
cd = float(input('Enter the Conductivity: '))
oc = float(input('Enter the Organic_carbon: '))
tm = float(input('Enter the Trihalomethanes: '))
tb = float(input('Enter the Turbidity: '))

query_point = np.array([ph,hd,sd,cl,sl,cd,oc,tm,tb]).reshape(1, -1)

query_point_transformed = scaler.transform(query_point)

nb_classifier.predict(query_point_transformed)

Enter Water Details
Enter the ph: 9.80
Enter the Hardness: 98.77
Enter the Solids: 27357.45
Enter the Chloramines: 9.21
Enter the Sulphate: 323.19
Enter the Conductivity: 512.42
Enter the Organic_carbon: 14.16
Enter the Trihalomethanes: 59.45
Enter the Turbidity: 2.76


C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)